customers/urls.py
from django.urls import path
from .views import CustomerAPIView, CustomerRetrieveAPIView

app_name = "customers"

urlpatterns = [
    path('', CustomerAPIView.as_view(), name='list'),
    path('<int:id>/', CustomerRetrieveAPIView.as_view(), name='detail'),
]

oowlish/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls.static import static
from django.conf import settings
from graphene_django.views import GraphQLView

swagger_info = openapi.Info(
    title="Customers API",
    default_version='v1',
    description="A Customers API Implementation",
    terms_of_service="https://www.google.com/policies/terms/",
    contact=openapi.Contact(email="lfniederauer@gmail.com"),
    license=openapi.License(name="MIT"),
)

SchemaView = get_schema_view(
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    re_path('^swagger(?P<format>.json|.yaml)$',
            SchemaView.without_ui(cache_timeout=0),
            name='schema-json'),
    path('swagger/',
         SchemaView.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/',
         SchemaView.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
    path("graphql", GraphQLView.as_view(graphiql=True), name='graphql'),
    path('admin/', admin.site.urls),
    path('customers/',
         include('customers.urls', namespace='customers')),
    path('', TemplateView.as_view(template_name='home.html'),
         name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customers/models.py
from django.db.models import (Model,
                              CharField,
                              DecimalField,
                              EmailField,
                              TextChoices)


class Customer(Model):
    """
    Simple model provided as is.
    """
    Genders = TextChoices('Female', 'Male')
    first_name = CharField("customer's first name", max_length=62)
    last_name = CharField("customer's last name", max_length=62)
    email = EmailField("customer's email")
    gender = CharField("customer's gender", choices=Genders.choices,
                       max_length=6)
    company = CharField("customer's company name", max_length=62)
    city = CharField("customer's first name", max_length=62)
    title = CharField("customer's first name", max_length=62)
    lat = DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    lon = DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = "Customer",
        verbose_name_plural = "Customers"

customers/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView
from .models import Customer
from .serializers import CustomerSerializer


class CustomerAPIView(ListAPIView):
    """
    This view returns the customers list in JSON.
    """
    serializer_class = CustomerSerializer
    queryset = Customer.objects.all()
    http_method_names = [u'get', u'head', u'options']


class CustomerRetrieveAPIView(RetrieveAPIView):
    """
    This view returns a particular customers according to the id.
    """
    serializer_class = CustomerSerializer
    lookup_field = 'id'
    queryset = Customer.objects.all()
    http_method_names = [u'get', u'head', u'options']

templates/base.html
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>{% block head_title %}Test OOW{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1;" charset="UTF-8" />
    <meta name="robots" content="follow">

    <meta name="description" content="Test">
    <meta name="author" content="lfniederauer">
    <meta name="copyright" content="2021">

    {% block pagecss %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock pagecss %}
</head>
<body>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    {% block endjs %} {% endblock endjs %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block head_title %}Oowlish | {{ block.super }}{% endblock head_title%}

{% block content %}
<main>
    <section>
        <div class="container g-pt-20 g-pb-20">
            <div class="g-bg-secondary row justify-content-center g-pt-40 g-pb-40 g-mb-60">
                <div class="col-lg-7">
                    <div>
                        <h2 class="g-color-black text-uppercase mb-2">OOWLISH DEMO</h2>
                        <br>
                        <p>
                            <a href="{% url 'schema-json' format='.json' %}"
                               class="g-color-white g-color-primary--hover g-text-underline--none--hover">
                                schema-json
                            </a>
                        </p>
                        <p>
                            <a href="{% url 'schema-swagger-ui' %}"
                               class="g-color-white g-color-primary--hover g-text-underline--none--hover">
                                schema-swagger-ui
                            </a>
                        </p>
                        <p>
                            <a href="{% url 'schema-redoc' %}"
                               class="g-color-white g-color-primary--hover g-text-underline--none--hover">
                                schema-redoc
                            </a>
                        </p>
                        <p>
                            <a href="{% url 'graphql' %}"
                               class="g-color-white g-color-primary--hover g-text-underline--none--hover">
                                GraphQL Customer List
                            </a>
                        </p>
                        <p>
                            <a href="{% url 'customers:list' %}"
                               class="g-color-white g-color-primary--hover g-text-underline--none--hover">
                                Json Raw Customer List
                            </a>
                        </p>
                        <p>
                            <a href="{% url 'customers:detail' id=3 %}"
                               class="g-color-white g-color-primary--hover g-text-underline--none--hover">
                                Json Customer Detail ID=3
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock content %}